In [1]:
#set : 元素不可重複，兩個set可進行集合運算(聯集等)
set1: set = {1,1,3,3,5,7,9}
set1.add(11)
set1

{1, 3, 5, 7, 9, 11}

In [3]:
import numpy as np
#numpy數值運算，進行科學、統計運算(常態分布)
array1: np.ndarray= np.array(range(1,11))

#陣列運算
array1 +10 *50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [4]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [5]:
#亂數
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.18514403865274376

array([[[ 0.28634193,  0.18887085,  0.53669934],
        [-0.26982669, -0.9206665 ,  1.37287085],
        [-0.54532515,  0.35443649, -1.23362412],
        [ 0.96854444, -0.04920092, -0.04070021],
        [-1.07435643, -0.59551952,  1.20219447]],

       [[-0.61655855, -0.82519999, -0.14773342],
        [ 0.38106625,  0.82969054, -1.18933035],
        [-0.33978169,  2.18883553,  0.14129808],
        [ 1.46349611,  0.55639861,  2.35754157],
        [ 1.8195535 , -0.17831045,  1.6020716 ]],

       [[-1.00381586,  0.59625941, -2.06227566],
        [ 1.33965367, -0.83589087, -0.24440645],
        [ 1.91658106,  0.41502991,  0.37665784],
        [ 0.88535404,  1.24972985,  0.82699944],
        [-0.16315147,  0.67538572, -0.03668966]],

       [[-0.40288635,  1.93846511,  0.94968281],
        [-0.07854727,  1.65808306, -0.84971498],
        [ 1.33066517,  0.44223684, -0.05656177],
        [-0.21502286,  0.53059609,  0.83536026],
        [ 0.81244552,  0.1023465 , -0.53949607]],

       [[-0.

array([[9, 2, 9, 6, 5],
       [4, 5, 5, 9, 4],
       [5, 9, 2, 3, 3],
       [2, 4, 4, 5, 8],
       [6, 4, 4, 9, 1],
       [4, 5, 3, 6, 5],
       [1, 8, 1, 8, 2],
       [9, 2, 4, 9, 5],
       [9, 8, 2, 3, 4],
       [7, 9, 2, 8, 1]])